### PR TITLE
Fix (core-ui): Component Picker - the component items are flatten after first opening

### LINKED ISSUE #348: Component Picker: the component items are flatten after first opening
## Description 
Component Picker: the component item are flatten after first opening

### Steps to reproduce
1. open Edit env, Home page
2. switch to Edit mode
3. click in a tout item to get '+' in Editor Menu
4. click +
### Expected result
Screen Shot 2020-05-19 at 4 51 35 PM

### Actual result
Screen Shot 2020-05-19 at 4 50 36 PM

### Note:
the items get to their normal view when some actions are made in Component picker: e.g. if search or filter is used, or if a component is selected and Component Picker is reopened after that.

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in [Master](https://github.com/johnsonandjohnson/Bodiless-JS/commit/455fd7c39be04ebe16ec2236ecb21b4785ca8af1)

### PR DESCRIPTION
**Pull request by konst8**
## Changes
Make the components in the picker to be flexible by height if the horizontal scale is 1.

## Test Instructions
Open component picker, make sure the components are not flattened.

## Related Issues
Fixes #348 #324

### CODE REVIEW

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx [hunk 1]
```diff
@@ -65,15 +65,17 @@ const ItemList: React.FC<ItemListProps> = props => {
 
   useEffect(() => {
     // Imitate nextTick() functionality to make sure components are fully mounted.
-    setTimeout(() => {
```
Comment (beliayeu) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:68]: @konst8, did you remove setTimeout on purpose?

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx [hunk 2]
```diff
@@ -65,15 +65,17 @@ const ItemList: React.FC<ItemListProps> = props => {
...
-      // eslint-disable-next-line no-undef
-      document.querySelectorAll('.bl-outerTransform').forEach(element => {
-        // we have to cast this so that we can use style and offsetHeight
-        const htmlElement = element as HTMLElement;
+    // We are in useEffect so we know document exists
+    // eslint-disable-next-line no-undef
+    document.querySelectorAll('.bl-outerTransform').forEach(element => {
+      // we have to cast this so that we can use style and offsetHeight
+      const htmlElement = element as HTMLElement;
+      if (scale === 1) {
```
Comment (beliayeu) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:73]: it would be nice to avoid having magic numbers

Comment (beliayeu) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:73]: it would be nice to add a comment explaining why the problem happens only for scale = 1 and does not happen on other scales

Comment (beliayeu) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:73]: I believe we mitigated the issue, but we did not solve it completely
per my understanding we may still get the issue once the scale is changed but images are not loaded yet by browser
I believe we should either make recalculation after all dependent assets are loaded or come up with another mechanism how to scale items

Comment (VancheeZze) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:73]: I'd also add that component picker most likely renders the components themselves, not pictures of them. So it could be that the client needs some extra time to render those components before the height could be set.

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx (hunk 1 above)
Comment (konst8) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:68]: Yes. I guess it was a try to fix the issue, which didn't work apparently.

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx (hunk 2 above)
Comment (konst8) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx]: Added height recalculation on image load.

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx [hunk 3]
```diff
@@ -65,15 +65,20 @@ const ItemList: React.FC<ItemListProps> = props => {
...
-        htmlElement.style.height = `${htmlElement.offsetHeight / scale}px`;
-      });
+    // We are in useEffect so we know document exists
+    // eslint-disable-next-line no-undef
+    document.querySelectorAll('.bl-outerTransform').forEach(element => {
+      // we have to cast this so that we can use style and offsetHeight
+      const htmlElement = element as HTMLElement;
+      htmlElement.style.height = '100%';
+      htmlElement.style.height = `${htmlElement.offsetHeight / scale}px`;
+      const img = htmlElement.querySelector('img');
```
Comment (beliayeu) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:75]: consider supporting
* images embedded using picture
* other Embedded content html elements (iframe, video, audio)
* elements containing multiple images

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx (hunk 1 above)
Comment (beliayeu) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:68]: @konst8, I think comment "Imitate nextTick() functionality to make sure components are fully mounted." above can be removed since it is related to setTimeout thing

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx (hunk 3 above)
Comment (konst8) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx]: Done. Should now recalculate on load of any asset that has 'src' attribute.

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx [hunk 4]
```diff
@@ -84,9 +60,7 @@ const ItemList: React.FC<ItemListProps> = props => {
             {Component.title || Component.displayName || 'Untitled'}
           </finalUI.TitleWrapper>
           <div className="bl-outerTransform bl-w-full bl-bg-white">
-            <div
-              style={transformStyle}
-            >
+            <div>
```
Comment (VancheeZze) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:63]: I would also remove this extra <div>

File: packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx [hunk 5]
```diff
@@ -145,14 +139,16 @@ const ItemList: React.FC<ItemListProps> = props => {
...
       </finalUI.ScalingHeader>
-      <finalUI.GridListBoxInner>
-        {elems}
-        {
-          components.length > 50
-            ? <MoreItems />
-            : Fragment
-        }
-      </finalUI.GridListBoxInner>
+      <div style={{ height: '500px' }}>
```
Comment (beliayeu) [inline packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:142]: it would be nice to add a comment why we setting the height to 500px

Comment (konst8) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:142]: @beliayeu Currently the whole picker form has static size:
https://github.com/johnsonandjohnson/Bodiless-JS/blob/master/packages/bodiless-ui/index.tailwind.css#L54
So, 500 - is the form height considering heading and paddings.

Comment (konst8) [reply packages/bodiless-layouts/src/ComponentSelector/ItemListScale.tsx:142]: To my mind, the form still needs some attention in terms of styling. But probably in the scope of another ticket.
