### PR TITLE
fix(migration_tool): issues in FAQ pages

### LINKED ISSUE #101: Migration tool: issues in FAQ pages
### Steps to reproduce
1. migrate [your site].com with migration-settings. json shown below
```
{
  "url": "https://[your site].com/",
  "crawler": {
    "maxDepth": 100,
    "maxConcurrency": 1,
    "ignoreRobotsTxt": true
  },
  "transformers": [
  	  	{
      "rule": "replace",
      "selector": "base",
      "replacement": "",
      "context": "**" 
    }
  ]
}
```
2. Run migration and serve the static site.

3. Go to pages with link fragment based accordion element, that allowing user to click open accordions. Click on accordion.

### Expected result

Accordion opens without page jumping.

### Actual result

page jumps

### PR DESCRIPTION
**Pull request by dewen**
## Changes

Fixing page scrolls to the top issue

### Step 1. Migrate site with accordion element on a FAQ page.

- Run migration script to generate pages.
```
cd examples/starter/
npm run migration
```
### Step 2. Configure the no-scroll settings on site level

- Edit no-scroll settings in 'src/@bodiless/gatsby-theme-bodiless/no-scroll-settings.json'

Sample settings:
```
{
  "parentSelectors": [
    ".bean-qa",
    ".bean-qa-1",
    ".bean-qa-2"
  ],
  "elementSelectors": [
  ],
  "excludeHashes": [
    "what-type-of-active-ingredients-hash"
  ]
}

```

### Step 3. Serve the static page and check FAQ page for jumping issue.

- Serve the static site
```
npm run build
npm run serve
```

- Review the change on pages with Accordions.

## Related Issues

Fixes #101

### CODE REVIEW

File: examples/starter/gatsby-browser.js [hunk 1]
```diff
@@ -19,3 +34,38 @@ if (enabled) {
     // Ignore error.
   }
 }
+
```
Comment (hvanyo) [inline examples/starter/gatsby-browser.js]: @dewen  Do we want this as part of Starter?  It doesn't seem applicable for every site.

File: examples/starter/gatsby-browser.js [hunk 2]
```diff
@@ -19,3 +34,51 @@ if (enabled) {
...
+      const targetElement = document.getElementById(hash) || document.getElementsByName(hash)[0];
+      const HashMatchException = {};
+
+      try {
+        // eslint-disable-next-line
+        const { parentSelectors, elementSelectors, excludeHashes } = require('./no-scroll-settings.json');
+
+        if (excludeHashes.indexOf(hash) < 0) {
+          // Skip scrolling for selected element.
+          elementSelectors.forEach(item => {
```
Comment (beliayeu) [inline examples/starter/gatsby-browser.js]: @dewen, probably we can ask site builders to set a list of hashes (not a list of elements). then we can just check if hash is included in the collection of hashes taken from no-scroll-settings

File: examples/starter/gatsby-browser.js (hunk 1 above)
Comment (beliayeu) [reply examples/starter/gatsby-browser.js]: @hvanyo, @dewen, to my mind we should move this logic to our private theme

File: examples/starter/gatsby-browser.js [hunk 3]
```diff
@@ -19,3 +34,51 @@ if (enabled) {
...
+      location: { pathname: oldPathname },
+    } = prevRouterProps;
+    if (oldPathname === location.pathname) {
+      const hash = location.hash ? location.hash.slice(1) : '';
+      if (!hash) {
+        return true;
+      }
+      const targetElement = document.getElementById(hash) || document.getElementsByName(hash)[0];
+      const HashMatchException = {};
+
```
[the remark this answers is not in the document]
Comment (dewen) [reply examples/starter/gatsby-browser.js]: I think the selector configure itself is enough, maintaining another environment variable might not be necessary.

File: examples/starter/gatsby-browser.js (hunk 1 above)
Comment (hvanyo) [reply examples/starter/gatsby-browser.js]: @dewen  per skype discussion let's move this gatsby-theme-bodiless theme. 
Let us know if there is issues with that.  

cc: @wodenx  @beliayeu

File: packages/gatsby-theme-bodiless/no-scroll-settings.json [hunk 4]
```diff
@@ -0,0 +1,8 @@
+{
```
Comment (beliayeu) [inline packages/gatsby-theme-bodiless/no-scroll-settings.json]: @dewen, to my mind the configuration file should be added to the site level

File: packages/gatsby-theme-bodiless/gatsby-browser.js [hunk 5]
```diff
@@ -28,7 +28,39 @@ export const shouldUpdateScroll = ({ prevRouterProps, routerProps: { location }
...
+      const HashMatchException = {};
+
+      try {
+        // eslint-disable-next-line
+        const { parentSelectors, elementSelectors, excludeHashes } = require('./no-scroll-settings.json');
+
+        if (excludeHashes.indexOf(hash) < 0) {
+          // Skip scrolling for selected element.
+          elementSelectors.forEach(item => {
+            document.querySelectorAll(item).forEach(element => {
```
Comment (beliayeu) [inline packages/gatsby-theme-bodiless/gatsby-browser.js]: @dewen, to my mind we can join elementSelectors to sting similar to what you did for parentselectors

File: packages/bodiless-migration-tool/doc/Technical/MigrationTool.md [hunk 6]
```diff
@@ -266,6 +266,38 @@ After performing of `npm run build`:
 
 Full examples can be found in [examples/settings](examples/settings).
 
+### Configure no-scroll for selected anchor element.
+
+Sometimes, migrated page contains foldable accordion elements that implemented with anchor fragment. By default GatsbyJS navigation compares the change in url and scrolls page to location base on given url hash.
```
Comment (hvanyo) [inline packages/bodiless-migration-tool/doc/Technical/MigrationTool.md]: Sites, undergoing flattening, may have foldable accordion elements that are implemented with anchor fragment.  By default, GatsbyJS navigation compares the change in url and scrolls the page to the location based on the given url hash.

File: packages/bodiless-migration-tool/doc/Technical/MigrationTool.md [hunk 7]
```diff
@@ -266,6 +266,38 @@ After performing of `npm run build`:
...
+
+If this is not the desired behavior for migrated page, user might override scrolling by configure `no-scroll-settings.json` and place it under `[site]/src/@bodiless/gatsby-theme-bodiless/` folder. Behind the scenes, it shadows Gatsby theme packages/gatsby-theme-bodiless/src/no-scroll-settings.json configure file.
```
Comment (hvanyo) [inline packages/bodiless-migration-tool/doc/Technical/MigrationTool.md]: for the migrated page

File: packages/bodiless-migration-tool/doc/Technical/MigrationTool.md [hunk 8]
```diff
@@ -266,6 +266,38 @@ After performing of `npm run build`:
...
+  ],
+  "excludeHashes": [
+    "hash-to-be-excluded-from-no-scrolling"
+  ]
+}
+
+```
+
+Notes,
+1. All hash anchors under classname ".container-classname-1" and ".container-classname-2" container will make page scrolling.
```
Comment (hvanyo) [inline packages/bodiless-migration-tool/doc/Technical/MigrationTool.md]: Rather than doing notes do "Explanation of options:"

- parentSelectors:  Contains a list of classnames that within this selector the page will scroll.
- elementSelectors:   Contains a list of classnames that disable the page scrolling.
- excludeHashes: Used to define a custom list of classnames that .. (?? not quite sure so fill in)

File: packages/bodiless-migration-tool/doc/Technical/MigrationTool.md [hunk 9]
```diff
@@ -266,6 +266,38 @@ After performing of `npm run build`:
...
+  ],
+  "excludeHashes": [
+    "hash-to-be-excluded-from-no-scrolling"
+  ]
+}
+
+```
+
+Explanation of options:,
+- `parentSelectors`: Contains a list of classnames that within this selector the page will scroll.
```
Comment (beliayeu) [inline packages/bodiless-migration-tool/doc/Technical/MigrationTool.md]: @dewen, probably it is better to replace classnames with selectors, since site builders can specify selectorString, not only classes

**Comment by wodenx** [comment]
## Test Results
- All tests executed using local packags on starter kit (ie after running
  ```
  npm run sites:clone-local starter
  npm run sites:update starter
  ```
- Used the following migration.settings.json:
  ```
  {
    "url": "https://www.neosporin.com/",
    "crawler": {
      "maxDepth": 100,
      "maxConcurrency": 1,
      "ignoreRobotsTxt": true
    },
    "transformers": [
      {
        "rule": "replace",
        "selector": "base",
        "replacement": "",
        "context": "**" 
      }
    ]
  }
  ```
- Initial migration:  edit `.env.site` to disable tailwind theme, run 'npm run migrate`
- For each test case, modified `src/@bodiless/gatsby-theme-bodiless/no-scroll-settings.json`
  and ran `npm run build && npm run serve`

### Test Cases
0.  No `no-scroll-settings.json` -- all FAQs scroll to top -- PASSED
1. Specify parent selector ".bean-qa" -- all FAQS do not scroll to top -- PASSED
2. Specify parent selector ".bean-qa" with exclude hashes -- Excluded FAQ tabs scroll to top -- PASSED
3. Specify element selector with exclude hashes -- all tabs do not scroll to top except excluded tabs.
4. Same as 3 but with parent selector set to a container with no tabs -- same behavior as #3 
5. Same as 4 but with no element selector - all tabs scroll to top -- PASSED

#### `no-scroll-settings.json` for each test case
[test1.txt](https://github.com/johnsonandjohnson/Bodiless-JS/files/4227195/test1.txt)
[test2.txt](https://github.com/johnsonandjohnson/Bodiless-JS/files/4227196/test2.txt)
[test3.txt](https://github.com/johnsonandjohnson/Bodiless-JS/files/4227197/test3.txt)
[test4.txt](https://github.com/johnsonandjohnson/Bodiless-JS/files/4227198/test4.txt)
[test5.txt](https://github.com/johnsonandjohnson/Bodiless-JS/files/4227199/test5.txt)
