### PR TITLE
fix (backend): Completely delete new pages on revert

### LINKED ISSUE #125: PDP page: 'revert changes' is not working - content is not deleted
## Description 
PDP page: 'revert changes' is not working - content is not deleted

### Steps to reproduce
1. start Test site, open /products/ page 
2. 'Add a New Page' - click '+ Page' in Left Menu
3. fill a page name. Click 'v' 
4. Once page is created, fill in some content: add title, fill Accordions; add image, etc.
5. Click Revert changes in Left Menu, click 'v' to confirm
6*. Refresh a page after a browser alert is shown (step to execute until AESQ-2536 is in master)

### Expected result
Content should be cleaned.

### Actual result
All content remains, the changes are not deleted

### Environment

 System:
    OS: macOS High Sierra 10.13.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.87
    Safari: 11.1
  npmGlobalPackages:
    gatsby-cli: 2.8.29

### Affected Version
reproduced in Master [14f9442938db7caa8124706e217bff7a5c762d9a](https://github.com/johnsonandjohnson/Bodiless-JS/commit/14f9442938db7caa8124706e217bff7a5c762d9a)

### PR DESCRIPTION
**Pull request by konst8**
## Changes
- Make sure new pages are completely deleted after resetting changes.
- Clean up deleted pages from the 'public' directory.

## Test Instructions
- create some new pages (with data or not)
- revert changes using UI button
- make sure the pages are deleted, page paths return 404, new pages can be created on the paths

## Related Issues
Fixes #125

### CODE REVIEW

File: packages/bodiless-backend/src/backend.js [hunk 1]
```diff
@@ -31,6 +31,7 @@ const backendFilePath = process.env.BODILESS_BACKEND_DATA_FILE_PATH || '';
 const defaultBackendPagePath = path.resolve(backendFilePath, 'pages');
 const backendPagePath = process.env.BODILESS_BACKEND_DATA_PAGE_PATH || defaultBackendPagePath;
 const backendStaticPath = process.env.BODILESS_BACKEND_STATIC_PATH || '';
+const backendPublicPath = process.env.BODILESS_BACKEND_PUBLIC_PAGE_PATH || 'public/page-data';
```
Comment (VancheeZze) [inline packages/bodiless-backend/src/backend.js:34]: I would add `BODILESS_BACKEND_PUBLIC_PAGE_PATH` to the `.env.site` for both `test-site` and `starter` since we try to keep all the env variables in there for ease of use and reference.

**Comment by TatsianaMiraniuk** [comment]
Hi @konst8,  
The following issue has been found - issue 1: Reverting the changes is not clearing /public/page-data

Scenario-1:
**Steps to reproduce:**
1. run Edit env, 
2. open Home page 
3. switch to Edit mode.
4. create a new page (on Home page), e.g page_1 -> /page_1 page loads
5. go to any page one level down of Home page, e.g. /products/
6. create a new page (on /products/), e.g. page_2 -> /products/page_2 page loads
7. click 'Revert the changes'. Confirm the reverting.
8. check /public/page-data and /src/data/pages

**Expected Results:**
both pages (/page_1 and /products/page_2 ) are deleted from /public/page-data and from /src/data/pages
**Actual Results:**
a page created from a page of lower level (/products/), /products/page_2 - is NOT deleted from  /public/page-data and can still be open.
Notes: 
1)a page created from Home page_1 is deleted from both /public/page-data and /src/data/pages;
2)a page created from a page of lower level (/products/), /products/page_2 - is deleted from /src/data/pages

Scenario-2:
**Steps to reproduce:**
1. run Edit env, 
2. open Home page 
3. switch to Edit mode.
4. go to any page one level down of Home page, e.g. /list/
5. create a new page (on /list/ page), e.g page_3 -> /list/page_3 page loads
6. go to any page one level down of Home page, e.g. /touts/
7. create a new page (on /touts/ page), e.g. page_4 -> /touts/page_4 page loads
8. click 'Revert the changes'. Confirm the reverting.
9. check /public/page-data and /src/data/pages

**Expected Results:**
both pages (/list/page_3 and /touts/page_4) are deleted from /public/page-data and from /src/data/pages
**Actual Results:**
both pages (/list/page_3 and /touts/page_4) are NOT deleted from /public/page-data and can still be open.
Both pages (/list/page_3 and /touts/page_4) are deleted only from /src/data/pages

Thanks,
Tatsiana

**Comment by TatsianaMiraniuk** [comment]
@konst8 

please see issue-2: a deleted page is still shown in a list of the existing pages in 404 gatsby page.

**Steps to reproduce:**

1. run Edit env,
2. open Home page
3. switch to Edit mode.
4. create a new page (on Home page), e.g page_5 -> /page_5 page loads
5. click 'Revert the changes'. Confirm the reverting.

**Expected Results:**
/page_5 is deleted and not shown in the list of the existing pages
**Actual Results:**
/page_5 is deleted BUT still shown in the list of the existing pages
Screen Shot 2020-06-16 at 4 59 18 PM

NOTE: 
the deleted page path gets removed from the list of the existing pages on 404 gatsby page with the next revert changes IF there are changes to be reverted. 
If no changes to be removed and we do a revert, the deleted page path is still shown

Thanks,
Tatsiana
