### PR TITLE
fix: Fix Content Library hover indicator missing

### LINKED ISSUE #1777: Content Library: 'Library Item' indicator is missing
**STR:**
1. open a page that has Content Library Flow Container, on Edit env, e.g /flow-container/ on Test Site or /styleguide/flow-container/ on Vital Demo
2. add a component into Content Library Flow Container
3. add the component to the Library

**AR:**
'Library Item' indicator is missing
Screen Shot 2022-05-10 at 2 00 57 PM

**ER:**
'Library Item' indicator is shown
https://github.com/johnsonandjohnson/Bodiless-JS/blob/242d1fe93876097a139ac07df63a37de612ccdbe/packages/bodiless-layouts/doc/assets/ContentLibraryItemAndContextMenu.jpg

### PR DESCRIPTION
**Pull request by lucas-varela**
## Changes
Fix an issue where the Content Library indicator wans't showing up on hover after adding a component in a library.

## Related Issues

Fixes #1777

### CODE REVIEW

File: packages/bodiless-layouts/src/ContentLibrary/ContentLibraryIndicator.tsx [hunk 1]
```diff
@@ -56,9 +56,9 @@ const LibraryIndicatorBase: FC<LibraryIndicatorProps> = ({ components: C, ...res
 export const LibraryItemIndicatorClean = designable(LibraryItemIndicatorComponents, 'LibraryItemIndicator')(LibraryIndicatorBase);
 
 const asDefaultLibraryItemIndicator = withDesign({
-  Wrapper: addClasses('bl-hidden group-hover:bl-flex bl-text-white bl-bg-gray-900 bl-absolute bl-px-2 bl-py-1 md:bl-mt-5 md:bl-ml-5 bl-z-10'),
+  Wrapper: addClasses('bl-hidden group-hover:bl-flex bl-items-center bl-text-white bl-bg-gray-900 bl-absolute bl-px-2 bl-py-1 md:bl--mt-5 md:bl--ml-5 bl-z-10'),
```
Comment (hvanyo) [inline packages/bodiless-layouts/src/ContentLibrary/ContentLibraryIndicator.tsx:59]: Are these suppose to have -- "md:bl--mt-5 md:bl--ml-5"

**Review by hvanyo — APPROVED** [review]

**Review by dewen — APPROVED** [review]
