### PR TITLE
fix(components): Fix invalid prop warning when toggling to a fragment in preview mode.

### LINKED ISSUE #354: Invalid prop warning on homepate
## STR
1. Open edit env home page

## ER
No warnings

## AR
```
index.js:2177 Warning: Invalid prop `design` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
    in Fragment (at hoc.tsx:29)
    in Unknown (at withNode.tsx:29)
    in NodeProvider (at withNode.tsx:28)
    in WithNode (at withFlowToggle.tsx:32)
    in wrappedComponent (at withFlowToggle.tsx:32)
    in wrappedComponent (at Toggle.tsx:43)
    in wrappedComponent (at withNode.tsx:25)
    in WithNode (at withFlowToggle.tsx:32)
    in wrappedComponent (at withNode.tsx:29)
    in NodeProvider (at withNode.tsx:28)
    in WithNode (at withNode.tsx:40)
    in WithNodeKey (at withChild.tsx:18)
    in Unknown (at Design.tsx:154)
    in WithDesign (at hoc.tsx:29)
    in Unknown (at Design.tsx:79)
    in Title (at List/index.tsx:70)
    in li (created by MenuItem)
    in MenuItem (created by Connect(MenuItem))
    in Connect(MenuItem) (at FClasses.tsx:110)
    in Stylable (at FClasses.tsx:47)
    in AddClasses (at FClasses.tsx:47)
    in AddClasses (at FClasses.tsx:47)
    in AddClasses (at asRCMenuSublist.tsx:45)
    in ItemWithoutSublist (at Toggle.tsx:43)
    in wrappedComponent (at Design.tsx:79)
    in Item (at List/index.tsx:37)
    in NodeProvider (at withNode.tsx:28)
    in WithNode (at List/index.tsx:36)
    in ItemWithNode (at List/index.tsx:69)
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (at FClasses.tsx:110)
    in Stylable (at addProps.tsx:22)
    in Unknown (at FClasses.tsx:47)
    in AddClasses (at addProps.tsx:22)
    in Unknown (at FClasses.tsx:47)
    in AddClasses (at Design.tsx:79)
    in Wrapper (at List/index.tsx:78)
    in BasicList (at Design.tsx:188)
    in Transformer (at Design.tsx:204)
    in Unknown (at withNode.tsx:29)
    in NodeProvider (at withNode.tsx:28)
    in List (at asEditableList.tsx:71)
    in Unknown (at Design.tsx:154)
    in WithDesign (at Design.tsx:154)
    in WithDesign (at Design.tsx:154)
    in WithDesign (at Design.tsx:154)
    in WithDesign (at Design.tsx:154)
    in WithDesign (at FClasses.tsx:47)
    in AddClasses (at Design.tsx:154)
    in WithDesign (at Design.tsx:79)
    in DesktopMenu (at header.tsx:72)
    in div (at header.tsx:71)
    in div (at FClasses.tsx:110)
    in Stylable (at Design.tsx:89)
    in Replaceable (at FClasses.tsx:47)
    in AddClasses (at FClasses.tsx:47)
    in AddClasses (at Design.tsx:79)
    in Wrapper (at header.tsx:63)
    in Header (at Design.tsx:188)
    in Transformer (at Design.tsx:204)
    in Unknown (at Design.tsx:154)
    in WithDesign (at Layout/index.jsx:74)
    in StaticQueryDataRenderer (at gatsby-browser-entry.js:38)
    in StaticQuery (at Layout/index.jsx:59)
    in Layout (at pages/index.tsx:46)
    in wrappedComponent (at Page.tsx:59)
    in div (at FClasses.tsx:110)
    in Stylable (at hoc-util.tsx:44)
    in Unknown (at FClasses.tsx:47)
    in AddClasses (at hoc-util.tsx:35)
    in Unknown (at ContextWrapper.tsx:38)
    in ContextWrapper (at ContextWrapper.tsx:42)
    in ContextWrapper (at Page.tsx:58)
    in PageContextProvider (at GitProvider.tsx:219)
    in GitProvider (at Page.tsx:57)
    in PageContextProvider (at hoc.tsx:90)
    in NewPageProvider (at Page.tsx:56)
    in PageContextProvider (at PageEditor.tsx:104)
    in PageEditor (at PageEditor.tsx:27)
    in PageEditor (at Page.tsx:55)
    in GatsbyPageProvider (at Page.tsx:54)
    in NodeProvider (at GatsbyNodeProvider.tsx:75)
    in NodeProvider (at GatsbyNodeProvider.tsx:74)
    in GatsbyNodeProvider (at Page.tsx:53)
    in wrappedComponent (at pages/index.tsx:45)
    in HomePage (created by HotExportedHomePage)
    in AppContainer (created by HotExportedHomePage)
    in HotExportedHomePage (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:56)
    in RouteHandler (at root.js:78)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:69)
    in RouteUpdates (at root.js:68)
    in EnsureResources (at root.js:66)
    in LocationHandler (at root.js:124)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:123)
    in Root (at root.js:132)
    in StaticQueryStore (at root.js:138)
    in _default (at app.js:67)
```

### LINKED ISSUE #398: There is a warning in a console 'Invalid prop `onContextMenu` supplied to `React.Fragment`' when switching from Edit to Preview Mode
## Description
There is a warning in a console 'Invalid prop `onContextMenu` supplied to `React.Fragment`' when switching from Edit to Preview Mode

### Steps to reproduce
1. open Edit env, any page
2. open a console in a web-browser
3. click Edit button to switch to Edit mode
4. click Edit button to switch to Preview mode
### Expected result
no warnings

### Actual result
there is a warning: 
'Invalid prop `onContextMenu` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.'
Screen Shot 2020-06-25 at 11 01 51 AM

### Environment

System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version

reproduced in Master

### LINKED ISSUE #403: /gallery-final/: There are 2 warnings in a console:  'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.' when loading the page
## Description
There are 2 warnings in a console: 
'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.' when loading /gallery-final/ page (Edit and Preview modes)

### Steps to reproduce
1. open Edit env, /gallery-final/ page
2. open a console in a web-browser

### Expected result
no warnings

### Actual result
there are two warnings in a console: 
'Warning: Invalid prop `fClasses` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
In Preview and Edit modes
Screen Shot 2020-06-28 at 4 52 44 PM

### Environment
System:
OS: macOS High Sierra 10.13.4
CPU: (4) x64 Intel(R) Core(TM) i7-5650U CPU @ 2.20GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
Yarn: 1.17.0 - /usr/local/bin/yarn
npm: 6.14.1 - ~/.nvm/versions/node/v10.15.0/bin/npm
Languages:
Python: 2.7.10 - /usr/bin/python
Browsers:
Chrome: 81.0.4044.138
Safari: 11.1
npmGlobalPackages:
gatsby-cli: 2.8.29

### Affected Version
reproduced in Master

### PR DESCRIPTION
**Pull request by wodenx**
## Changes
- Strip all props from fragments when supplied as default components or off state in toggles.
- Fix incorrect use of applying classes to a Fragment and updated doc (Development/Guides/SiteBuildBasics?id=rich-text)

## Related Issues
fixes #354 
fixes #398 
fixes #403

### CODE REVIEW

File: packages/bodiless-core/src/hoc.tsx [hunk 1]
```diff
@@ -30,6 +30,20 @@ export const withoutProps = <Q extends object>(keys: string[]) => (
   )
 );
 
+/**
+ * Creates an HOC which strips all but hte speciried props.
```
Comment (dewen) [inline packages/bodiless-core/src/hoc.tsx:34]: "but the specified"

Comment (hvanyo) [reply packages/bodiless-core/src/hoc.tsx:34]:
```suggestion
 * Creates an HOC which strips all but the specified props.
```

**Comment by hvanyo** [comment]
@wodenx  -- I missed a page in my testing yesterday -> https://edit.mfrauaqgmy-jvaff4bu65vgm.us-2.platformsh.site/gallery-final is still throwing the error.
