### PR TITLE
fix: replace colon in json file names

### LINKED ISSUE #723: Replace colon in json file name
## Description

Some meta file names contain colon character which might cause issues on windows based system. So these colons should be replace with more common characters like hyphens "-".

### Steps to reproduce

- Check json files under folder - ./examples/test-site/src/data/site/

### Expected result

No ":" in json file names

### Actual result

```
./examples/test-site/src/data/site/meta$og:sitename.json
./examples/test-site/src/data/site/meta$og:type.json
./examples/test-site/src/data/site/meta$twitter:card.json
./examples/test-site/src/data/site/meta$twitter:site.json
```

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

### Affected Version

- If the issue was encountered on a site, please attach your `package.json`
- If the issue was encountered in the Bodiless-JS repo, please link to a
  commit or branch on which the issue occurs.

### PR DESCRIPTION
**Pull request by beliayeu**
## Changes
* replaced colon with hyphen in test-site json files
* updated metatags  nodekeys containing colons
* updated migration tool metatag scraper plugin with colon replacement

## Related Issues

Fixes #723

### CODE REVIEW

**Review by VancheeZze — APPROVED** [review]

File: packages/bodiless-migration-tool/src/plugins/metatags.ts [hunk 1]
```diff
@@ -47,10 +47,15 @@ const onPageCreate = ({
     .toArray()
     .filter(item => item.attribs.name !== undefined && item.attribs.content !== undefined)
     .filter(item => !names || names.includes(item.attribs.name))
+    .map(item => ({
+      // replace colon with hyphen to avoid issues on windows
```
Comment (dewen) [inline packages/bodiless-migration-tool/src/plugins/metatags.ts:51]: not sure if we need loop through all items for replacement, instead maybe just replace inline on LINE56:
```
const filename = item.attribs.name || item.attribs.property;
...
path.resolve(api.getPagePath(), `${prefix}$${filename.replace(':', '-')}.json`),
```

this way we could handle additional tag attribute process.

Comment (beliayeu) [reply packages/bodiless-migration-tool/src/plugins/metatags.ts:51]: hey @dewen, nice catch
I think it will lead also to changing the filtering logic (defined in line 48)
currently, the metatag plugin supports only standard attributes, it supports only metatags that have 'name' and 'content'. ('property' is not a standard attribute, see https://html.spec.whatwg.org/multipage/semantics.html#the-meta-element)
per discussion in #645, the decision was taken to implement support of non-standard attributes including 'property' in a separate ticket. I guess you created a ticket for it.
lets discuss if we want doing it as part of this ticket

**Review by dewen — APPROVED** [review]
