### PR TITLE
fix(richtext): [GAP] 2 clicks are needed on a newly created menu item to open Local context menu #671

### LINKED ISSUE #671: [GAP]: 2 clicks are needed on a newly created menu item to open Local context menu
## Description
**Steps to reproduce:**
 //=== for a clean page===
 1. Open /megamenu/ in Edit mode
 2. Click a top menu item 
 *Expected Results:*
 Local Context Menu is open.
 *Actual Results:*
 Local Context Menu is not shown

 

//=== for a page that has content in Menu===
 1. Open /megamenu/ in Edit mode
 2. Click a top menu item 
 3. Click "+Add"
 4. Click on the newly created item
 *Expected Results:*
 Local Context Menu is open.
 *Actual Results:*
 Local Context Menu is not shown. Second click is needed.

 

Please see [Video](https://jnj.sharepoint.com/teams/BodilessJS/Shared%20Documents/Forms/AllItems.aspx?id=%2Fteams%2FBodilessJS%2FShared%20Documents%2FTesting%2FVideos%2FMegaMenu2clicks%2Emov&parent=%2Fteams%2FBodilessJS%2FShared%20Documents%2FTesting%2FVideos)

### PR DESCRIPTION
**Pull request by marcopagliarulo**
## Changes
Prevent the on change state handler to save the data when it is the initial value and it has not been changed.
Preventing the unnecessary write data resolved the double clicks required to focus a newly created menu item.
The default Value provided to the richtext editor is converted to a new object to prevent focus issues on multi instance slate when the default value is identical between instances.

## Test Instructions
//=== for a clean page===

1. Open /megamenu/ in Edit mode
2. Click a top menu item
**Expected Results:**
Local Context Menu is open.
 
//=== for a page that has content in Menu===
1. Open /megamenu/ in Edit mode
2. Click a top menu item
3. Click "+Add"
4. Click on the newly created item
**Expected Results:**
Local Context Menu is open.

## Related Issues
Fixes #671

### CODE REVIEW

File: packages/bodiless-richtext/src/useNodeStateHandlers.ts [hunk 1]
```diff
@@ -59,20 +61,32 @@ const preserveAll = {
...
+    // The new value is identical to the initialValue.
+    const newValueNotInitial = !isEqual(initialValue.document, jsonValue.document);
+    // The new value is identical to the initialValue.
+    // But the document and new Value are different.
+    // So the new value is anyway a change from a previous state.
+    const newValueEmpty = !newValueNotInitial && document && !isEqual(document, jsonValue.document);
+
+    if (newValueEmpty
+      || (newValueNotInitial && (!document
+      || !isEqual(document, jsonValue.document)))
```
Comment (VancheeZze) [inline packages/bodiless-richtext/src/useNodeStateHandlers.ts:89]: This part works great, maybe we can simplify it. No need to reverse `newValueNotInitial` twice, it becomes harder to read. Instead, we could do something like this:
```js
// If Document has changed
const isDocumentChanged = !isEqual(document, jsonValue.document);

// If the value is initial value
const isNewValueInitial = isEqual(initialValue.document, jsonValue.document);

// If New Value is Empty
const isNewValueEmpty = isNewValueInitial && document && isDocumentChanged;

// If New Value Has Changes
const isNewValueChanged = !isNewValueInitial && (!document || isDocumentChanged);

if (isNewValueEmpty || isNewValueChanged) {
  node.setData({ document: jsonValue.document! });
}
```

**Review by VancheeZze — CHANGES_REQUESTED** [review]

File: packages/bodiless-richtext/src/useNodeStateHandlers.ts (hunk 1 above)
Comment (marcopagliarulo) [reply packages/bodiless-richtext/src/useNodeStateHandlers.ts]: Thanks @VancheeZze, your suggestion is definitely much better. Implemented and tested.

**Review by VancheeZze — APPROVED** [review]

**Review by TatsianaMiraniuk — APPROVED** [review]
